[package]
# Semantic Versionning is used: https://semver.org/
version = "1.1.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Cornell Box Maker"
description="Make a cornell box and customize its appearance and dimensions"
icon = "data/icon.png"
preview_image = "data/preview.png"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Modelling"

# Keywords for the extension
keywords = ["Box", "Cornell", "Maker"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import funkyboy.cornell.box".
[[python.module]]
name = "funkyboy.cornell.box"
